export const ROUTES = {
  Splash: 'Splash',
  Onboarding: 'Onboarding',
  AccountType: 'AccountType',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  Verification: 'Verification',
  ResetPassword: 'ResetPassword',
  Home: 'Home',
  ShopDetails: 'ShopDetails',
  ProductDetail: 'ProductDetail',
  Shops: 'Shops',
  Favorite: 'Favorite',
  Groceries: 'Groceries',
  EditAddress: 'EditAddress',
  MyCart: 'MyCart',
  SetLocationOnMap: 'SetLocationOnMap',
  Checkout: 'Checkout',
  OrderAccepted: 'OrderAccepted',
  Lists: 'Lists',
  List: 'List',
  AddList: 'AddList',
  Riders: 'Riders',
  RiderDetails: 'RiderDetails',
  OrderTracking: 'OrderTracking',
  OrderDetails: 'OrderDetails',
  OrderTrack: 'OrderTrack',
  AddFeedback: 'AddFeedback',
  AddTip: 'AddTip',
  ChatRoom: 'ChatRoom',
  Notification: 'Notification',
  Settings: 'Settings',
  EditProfile: 'EditProfile',
  NotificationSetting: 'NotificationSetting',
  ChangePassword: 'ChangePassword',
  DeleteAccount: 'DeleteAccount',
  PrivacyPolicy: 'PrivacyPolicy',
  TermsOfService: 'TermsOfService',
  HelpCenter: 'HelpCenter',
  CompleteProfile: 'CompleteProfile',
  ShopMyOrders: 'ShopMyOrders',
  CompletedOrders: 'CompletedOrders',
  ShopNewOrders: 'ShopNewOrders',
  TotalEarnings: 'TotalEarnings',
  ShopOwnerProducts: 'ShopOwnerProducts',
  AddProduct: 'AddProduct',
  ManageStock: 'ManageStock',
  BankDetail: 'BankDetail',
  DriverMyOrders: 'DriverMyOrders',
  DriverListOrderDetail: 'DriverListOrderDetail',
  DriverNewOrders: 'DriverNewOrders',
  AddBank: 'AddBank',
  MyWallet: 'MyWallet',
  ChatInbox: 'ChatInbox',
  MapNavigete: 'MapNavigete',
  UserListOrderDetail: 'UserListOrderDetail',
};

export const STACKS = {
  Auth: 'Auth',
  Main: 'Main',
};

export const TABS = {
  HomeTab: 'HomeTab',
  BuyTab: 'BuyTab',
  ClipboardTab: 'ClipboardTab',
  OrdersTab: 'OrdersStack',
  ProfileTab: 'ProfileTab',
  // Grocery Owner
  OrdersTab: 'OrdersTab',
  ProductsTab: 'ProductsTab',
  GroceryOwnerOrdersTab: 'GroceryOwnerOrdersTab',
};

export const CURRENCY_UNIT = '$';

export const STRIPE_COUNTRIES = [
  {label: 'Australia', value: 'Australia'},
  {label: 'Austria', value: 'Austria'},
  {label: 'Belgium', value: 'Belgium'},
  {label: 'Brazil', value: 'Brazil'},
  {label: 'Bulgaria', value: 'Bulgaria'},
  {label: 'Canada', value: 'Canada'},
  {label: 'Croatia', value: 'Croatia'},
  {label: 'Cyprus', value: 'Cyprus'},
  {label: 'Czech Republic', value: 'Czech Republic'},
  {label: 'Denmark', value: 'Denmark'},
  {label: 'Estonia', value: 'Estonia'},
  {label: 'Finland', value: 'Finland'},
  {label: 'France', value: 'France'},
  {label: 'Germany', value: 'Germany'},
  {label: 'Greece', value: 'Greece'},
  {label: 'Hong Kong', value: 'Hong Kong'},
  {label: 'Hungary', value: 'Hungary'},
  {label: 'Ireland', value: 'Ireland'},
  {label: 'Italy', value: 'Italy'},
  {label: 'Japan', value: 'Japan'},
  {label: 'Latvia', value: 'Latvia'},
  {label: 'Lithuania', value: 'Lithuania'},
  {label: 'Luxembourg', value: 'Luxembourg'},
  {label: 'Malta', value: 'Malta'},
  {label: 'Mexico', value: 'Mexico'},
  {label: 'Netherlands', value: 'Netherlands'},
  {label: 'New Zealand', value: 'New Zealand'},
  {label: 'Norway', value: 'Norway'},
  {label: 'Poland', value: 'Poland'},
  {label: 'Portugal', value: 'Portugal'},
  {label: 'Romania', value: 'Romania'},
  {label: 'Singapore', value: 'Singapore'},
  {label: 'Slovakia', value: 'Slovakia'},
  {label: 'Slovenia', value: 'Slovenia'},
  {label: 'Spain', value: 'Spain'},
  {label: 'Sweden', value: 'Sweden'},
  {label: 'Switzerland', value: 'Switzerland'},
  {label: 'Thailand', value: 'Thailand'},
  {label: 'United Kingdom', value: 'United Kingdom'},
  {label: 'United States', value: 'United States'},
];
